const PAGE_ID='northbridge-page-shell';

type Page={title:string;eyebrow:string;body:string;actions?:string[]};
const pages:Record<string,Page>={
  '/personal':{eyebrow:'PERSONAL FINANCE',title:'Personal account tools',body:'Review your account information, balance overview and everyday financial activity in one organized workspace.',actions:['View account balance','Account activity']},
  '/business':{eyebrow:'BUSINESS FINANCE',title:'Business banking workspace',body:'A dedicated place to review business account information and organize financial activity across devices.',actions:['Business overview','Account activity']},
  '/services':{eyebrow:'OUR SERVICES',title:'Financial tools in one place',body:'Explore the Northbridge Trust prototype services for account organization, digital transfers, cards, payments and financial insights.',actions:['Account overview','Cards & payments']},
  '/about':{eyebrow:'ABOUT NORTHBRIDGE',title:'Built around clarity and control',body:'Northbridge Trust is presented here as a functional financial-services website prototype focused on clear account information and responsive digital access.'},
  '/activity':{eyebrow:'ACCOUNT ACTIVITY',title:'Recent activity',body:'Your recent account activity is shown here for review. This prototype does not move or transfer real money.'},
  '/cards':{eyebrow:'CARDS & PAYMENTS',title:'Cards and payment activity',body:'Review card-related information in one organized view. No real card or payment transactions are processed by this prototype.'},
  '/profile':{eyebrow:'PROFILE',title:'Account profile',body:'Review the profile information saved for this browser account.'},
  '/send':{eyebrow:'SEND',title:'Send money',body:'This prototype page is for interface demonstration only. It does not initiate or process real money transfers.'},
  '/receive':{eyebrow:'RECEIVE',title:'Receive money',body:'This prototype page is for interface demonstration only. It does not create real payment instructions or receive real funds.'},
  '/deposit':{eyebrow:'DEPOSIT',title:'Deposit',body:'This prototype page demonstrates the deposit interface only. No real funds are deposited or transferred.'},
  '/more':{eyebrow:'ACCOUNT TOOLS',title:'More account options',body:'Additional account tools can be organized here without leaving the main account experience.'}
};

function go(path:string){window.location.hash=path;}
function remove(){document.getElementById(PAGE_ID)?.remove();document.documentElement.classList.remove('northbridge-page-open');}
function render(path:string){const page=pages[path];if(!page){remove();return;}remove();const shell=document.createElement('div');shell.id=PAGE_ID;shell.className='northbridge-page-shell';shell.innerHTML=`<div class="northbridge-page-inner"><header><button class="northbridge-back" aria-label="Go back">← Back</button><div class="northbridge-page-brand"><strong>NORTHBRIDGE TRUST</strong><span>FINANCIAL</span></div><button class="northbridge-home">Account</button></header><main><span class="eyebrow">${page.eyebrow}</span><h1>${page.title}</h1><p>${page.body}</p>${page.actions?.map(a=>`<button class="northbridge-page-action" data-action="${a}">${a}</button>`).join('')||''}<div class="northbridge-page-notice">Functional website demonstration — no real money is transferred.</div></main></div>`;document.body.appendChild(shell);document.documentElement.classList.add('northbridge-page-open');shell.querySelector('.northbridge-back')?.addEventListener('click',()=>{history.back()});shell.querySelector('.northbridge-home')?.addEventListener('click',()=>go('/dashboard'));shell.querySelectorAll<HTMLButtonElement>('.northbridge-page-action').forEach(b=>b.addEventListener('click',()=>{const text=b.dataset.action||'';if(text.toLowerCase().includes('balance')||text.toLowerCase().includes('overview'))go('/dashboard');else if(text.toLowerCase().includes('activity'))go('/activity');else if(text.toLowerCase().includes('cards'))go('/cards')}));}
function routeFromHash(){const h=window.location.hash||'#/';if(h.startsWith('#/'))render(h.slice(1));else remove();}
function mapTarget(target:Element):string|null{const el=target.closest('a,button') as HTMLElement|null;if(!el)return null;const href=(el.getAttribute('href')||'').replace(/^#/,'');if(pages[href])return href;const text=(el.textContent||'').trim().toLowerCase();if(text==='personal')return '/personal';if(text==='business')return '/business';if(text==='services')return '/services';if(text==='about')return '/about';if(text==='send')return '/send';if(text==='receive')return '/receive';if(text==='deposit')return '/deposit';if(text==='more')return '/more';if(text==='activity'||text==='view all')return '/activity';if(text==='cards')return '/cards';if(text==='profile')return '/profile';return null;}
function boot(){document.addEventListener('click',e=>{if((e.target as HTMLElement).closest('#'+PAGE_ID))return;const path=mapTarget(e.target as Element);if(!path)return;e.preventDefault();e.stopPropagation();go(path)},true);window.addEventListener('hashchange',routeFromHash);routeFromHash();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();